### ISSUE TITLE
Remove extra space in raw message before parsing

### ISSUE THREAD

**Issue by pveyes** [traveloka/slack-robot#2]
Add filter below this line https://github.com/traveloka/slack-robot/blob/master/src/Request.js#L97

Don't forget to add tests as we need 100% test coverage :smile:

**Comment by drgx** [comment]
97cd944fa9c966f4e9899f4c0eb79e962dd4366e

**Comment by pveyes** [comment]
Wow that was fast, you should consider using issue commit hook to close
issue via commit message 👍

On Tue, Sep 8, 2015, 21:22 Ryan Nixon Salim <notifications@github.com>
wrote:

> 97cd944
> <https://github.com/traveloka/slack-robot/commit/97cd944fa9c966f4e9899f4c0eb79e962dd4366e>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traveloka/slack-robot/issues/2#issuecomment-138578046>
> .
>
-- 

Fatih Kalifa

**Comment by drgx** [comment]
97cd944fa9c966f4e9899f4c0eb79e962dd4366e

**Comment by drgx** [comment]
97cd944fa9c966f4e9899f4c0eb79e962dd4366e

**Comment by pveyes** [comment]
Hi @drgx I just realized that your additional test doesn't use different `slackMessage` variable, it still use global test variable therefore test always passed.

Can you update your test? I've added some inline comment on your commit before

**Comment by drgx** [comment]
hi @pveyes, i already update my test, can you review my test for this issue?

**Comment by pveyes** [comment]
Actually it's prefered to use different local variable for `slackMessage`
